name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: josrafael  # Substitua pelo seu nome de usuário do Docker Hub
        password: 38714843Qaz  # Substitua pela sua secret do Docker Hub

    - name: Build and push Docker image
      run: |
        docker build -t josrafael/my-deploy-app:latest .
        docker push josrafael/my-deploy-app:latest

    - name: Deploy to VPS
      env:
        SSH_PRIVATE_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCnOpYvrC+FiwF+2zWu7eOObpI5m6iysDnLLWYcvN3GSxBJ5lj21ud29gWLHXWUmij32V4rTEgAF96pYiwFMRts9qOL4u6TSR0EYTABcE9byUKGu3R8gpsaGqI2pyUyLQgHdrAkZYr90ydDx1frNdBmKodhd7WJkU8JkI9pGbuX7nnIfRuF3rdUb7RgEOZhNNoN+RdmTOWAvvujQ+znGFogWQmRZ2DnTg2uQzWS6JVmNrsb6AuJ05L7PDHm7wpT24/TdgXJ9jSm0DlRZsK9dwfxJDlT2U2I9m7fEWgKLOZ0I/E+JS4xFlzBL8IYJp4oFb2vAwxE3dFQW5fpgyghTWBW38fdGPe2q87N9pusTcvuBTpdu8TgO2YvZPFtvDM3YX460iPOrMNwcwOWO2Xe30kI7LEf6CzOOT3Mkoep6PBKGbvmgWZKYv1Akt6Ap0RH4efxWX8dLtDboyJY0nVSd7EdZBudu7xxXBI7F3mPoiY3y0oSSYCgrk3Y7tfaR+j27sPKqDPbsKqm/WTSCzikNchGAqrWvwzUeeBLPicnF3XaQBWwHPWB8LFfjp94Jg2/e8PzCmWUkMbv7ownSJvLfMe6NAiHx/MTy9tqiXeXKHsYmHgDPi+MBic79TuWfqKlXu39tNlBbPhOKRizKbI3fOXrlFoTfELYNQtsdLY92G7fsw== rafaelmatiashue@gmail.com
        SSH_HOST: 195.200.4.214
        SSH_USERNAME: root
      run: |
        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCnOpYvrC+FiwF+2zWu7eOObpI5m6iysDnLLWYcvN3GSxBJ5lj21ud29gWLHXWUmij32V4rTEgAF96pYiwFMRts9qOL4u6TSR0EYTABcE9byUKGu3R8gpsaGqI2pyUyLQgHdrAkZYr90ydDx1frNdBmKodhd7WJkU8JkI9pGbuX7nnIfRuF3rdUb7RgEOZhNNoN+RdmTOWAvvujQ+znGFogWQmRZ2DnTg2uQzWS6JVmNrsb6AuJ05L7PDHm7wpT24/TdgXJ9jSm0DlRZsK9dwfxJDlT2U2I9m7fEWgKLOZ0I/E+JS4xFlzBL8IYJp4oFb2vAwxE3dFQW5fpgyghTWBW38fdGPe2q87N9pusTcvuBTpdu8TgO2YvZPFtvDM3YX460iPOrMNwcwOWO2Xe30kI7LEf6CzOOT3Mkoep6PBKGbvmgWZKYv1Akt6Ap0RH4efxWX8dLtDboyJY0nVSd7EdZBudu7xxXBI7F3mPoiY3y0oSSYCgrk3Y7tfaR+j27sPKqDPbsKqm/WTSCzikNchGAqrWvwzUeeBLPicnF3XaQBWwHPWB8LFfjp94Jg2/e8PzCmWUkMbv7ownSJvLfMe6NAiHx/MTy9tqiXeXKHsYmHgDPi+MBic79TuWfqKlXu39tNlBbPhOKRizKbI3fOXrlFoTfELYNQtsdLY92G7fsw== rafaelmatiashue@gmail.com" > key.pem
        chmod 600 key.pem
        ssh -i key.pem -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST "
          docker pull josrafael/my-deploy-app:latest &&
          docker stop root_app_1 || true &&
          docker rm root_app_1 || true &&
          docker run -d --name root_app_1 -p 3001:3001 josrafael/my-deploy-app:latest
        "
